language: rust
cache: cargo
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
    include:
        - os: windows
          rust: stable
        - os: windows
          rust: beta
        - os: windows
          rust: nightly
        - os: linux
          rust: stable
